name: Run Azure Login with GH OIDC
on: [push]

permissions:
      id-token: write
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:


        - name: Login via Azure login action using OIDC
          uses: 'azure/login@oidc-support'
          with:
                  client-id: ${{ secrets.CLIENT }}
                  tenant-id: ${{ secrets.TENANT }}
                  allow-no-subscriptions: true
        

        - name: 'Run az commands'
          run: |
                az account show
