name: Run Azure Login with GH OIDC
on: [push]

permissions:
      id-token: write
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:

        # windows Az CLI installation 
        - name: Install CLI-beta
          run: |
              cd ../..
              $CWD = Convert-Path .
              echo $CWD
              python --version
              python -m venv oidc-venv
              . .\oidc-venv\Scripts\Activate.ps1
              python -m pip install -q --upgrade pip
              echo "started installing cli beta" 
              pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
              echo "installed cli beta" 
              echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH

        - name: Login via Azure login action
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        

        - name: 'Run az commands'
          run: |
                az account show
